### PR TITLE
Added image rotation functionality. Cleaned up repository to improve builds.

### PR DESCRIPTION
**Pull request by collinprice**

### CODE REVIEW

**Comment by jwogan5** [comment]
@collinprice 

Hi collin,

Is there anyway you could build your module into a distribution zip with these changes. I really need the image rotation changes.  I'm building an app and on android portrait images are showing as landscape.

**Comment by ashcoding** [comment]
@jwogan5 
This seems like an old PR. Not sure how fast the author will reply but you could make this into a distribution zip on your own based on this guide http://docs.appcelerator.com/platform/latest/#!/guide/Android_Module_Project

**Comment by jwogan5** [comment]
@ashcoding 

Thanks for the link to the documentation. I haven't built a module yet but im looking forward to using the doc to build some other modules. I actually did find the link to collins build of 2.3.1 and it works great.

https://github.com/collinprice/ti.imagefactory/releases

**Comment by collinprice** [comment]
Great to hear @jwogan5

**Comment by julien9999** [comment]
how to rotate an image ?
thanks

**Comment by jwogan5** [comment]
@julien9999 

I am using an exif js file to get the rotation needed to flip the image correctly.  Here is the code not including that library that I am using to rotate images.

var rotate = 90; // Just a sample rotate integer degree.
var rotatedImage = ImageFactory.imageWithRotation(e.media, {degrees: rotate});

**Comment by jwogan5** [comment]
Here is a gist I just created with the exif.js file and a sample.js file:
https://gist.github.com/jwogan5/24d622a7f670ab57fcf983ab3ff2ecd8

**Comment by hansemannn** [comment]
@collinprice Hey man! I think it's about time to integrate this :-) Can you resolve the merge conflicts or should one of our devs help?

**Comment by collinprice** [comment]
@hansemannn Yay! I resolved the merge conflicts but it looks like travis failed for a different reason.

**Comment by hansemannn** [comment]
Merging now and will adjust the version and changelog afterwards.

**Pull request merged**
