### PR TITLE
[TIMOB-23598] Android: Recompile ti.imagefactory module against latest SDK

### PR DESCRIPTION
**Pull request by sgtcoolguy**
- V8 5.1.281.59
- Titanium SDK 6.0.0+
- Android NDK r11c
- Bumped version, apiversion, minsdk

### CODE REVIEW

**Comment by sgtcoolguy** [comment]
[ti.imagefactory-android-3.0.0.zip](https://github.com/appcelerator-modules/ti.imagefactory/files/357847/ti.imagefactory-android-3.0.0.zip)

https://github.com/appcelerator-modules/ti.imagefactory/tree/stable/android/example

I think this module may be deprecated and headed for the archive?

**Comment by ashcoding** [comment]
This is very weird (maybe just happening to me). I added the module into the project in Studio and I can't use it. It's not appearing anywhere. Hmm. Very strange.

**Comment by ashcoding** [comment]
Seems like I'm having issues with getting the other modules to appear. Hmmm.

**Comment by ashcoding** [comment]
Functionally tested when using a project from command line.
Working well.

**Comment by ashcoding** [comment]
Please merge. I do not have permission to merge this repo.

**Comment by fflores915** [comment]
> This is very weird (maybe just happening to me). I added the module into the project in Studio and I can't use it. It's not appearing anywhere. Hmm. Very strange.

I am getting the same issue with image factory 3.0.0. I have added the module in Appcelerator, but when I go to add the module the project nothing comes up. How did you resolve this?

**Comment by ashcoding** [comment]
@SOKGTECH this PR is for Titanium SDK 6 which is not GA yet.
What I found was actually a real issue and created a JIRA ticket. https://jira.appcelerator.org/browse/TISTUD-8534

You can follow the progress of it there. If you are not using Titanium SDK 6, please do not use version 3.0.0.

Alternatively, if you are intending to test it out, please run it from command line instead. In the root directory of the folder, after you edit the tiapp.xml manually to include version 3.0.0, you can run this command to run the app ```appc ti build run --platform android --log-level trace --target device```.

Hope that helps.

**Comment by SOKGTECH** [comment]
We were able to use this version to make it work on Android 6.0 using Titanium SDK 5.3.1 GA. 
[ti.imagefactory.zip](https://github.com/appcelerator-modules/ti.imagefactory/files/376526/ti.imagefactory.zip)

**Pull request merged**
